use std::collections::BTreeSet;
use std::path::Path;

/// Parsed form of a `${PORT_DBDIR}/<OPTIONS_NAME>/options` file as written
/// by `make config`.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SavedOptionsFile {
    /// `_OPTIONS_READ` (pkgname at the time the file was written).
    pub options_read: String,
    /// `_FILE_COMPLETE_OPTIONS_LIST`.
    pub complete: Vec<String>,
    pub set: BTreeSet<String>,
    pub unset: BTreeSet<String>,
}

impl SavedOptionsFile {
    pub fn parse(text: &str) -> Self {
        let mut out = SavedOptionsFile::default();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(v) = line.strip_prefix("_OPTIONS_READ=") {
                out.options_read = v.trim().to_string();
            } else if let Some(v) = line.strip_prefix("_FILE_COMPLETE_OPTIONS_LIST=") {
                out.complete = v.split_whitespace().map(str::to_string).collect();
            } else if let Some(v) = line.strip_prefix("OPTIONS_FILE_SET+=") {
                out.set.insert(v.trim().to_string());
            } else if let Some(v) = line.strip_prefix("OPTIONS_FILE_UNSET+=") {
                out.unset.insert(v.trim().to_string());
            }
        }
        out
    }

    pub fn load(path: &Path) -> Option<Self> {
        std::fs::read_to_string(path).ok().map(|t| Self::parse(&t))
    }
}

/// Render an options file exactly the way `make config` does: every option of
/// `complete` gets a SET or UNSET line, in `complete` order.
pub fn render(pkgname: &str, complete: &[String], enabled: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("# This file is auto-generated by 'make config'.\n");
    out.push_str(&format!("# Options for {pkgname}\n"));
    out.push_str(&format!("_OPTIONS_READ={pkgname}\n"));
    out.push_str(&format!("_FILE_COMPLETE_OPTIONS_LIST={}\n", complete.join(" ")));
    for opt in complete {
        if enabled.contains(opt) {
            out.push_str(&format!("OPTIONS_FILE_SET+={opt}\n"));
        } else {
            out.push_str(&format!("OPTIONS_FILE_UNSET+={opt}\n"));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
# This file is auto-generated by 'make config'.
# Options for qt5-speech-5.12.1_1
_OPTIONS_READ=qt5-speech-5.12.1_1
_FILE_COMPLETE_OPTIONS_LIST= SPEECHD FLITE
OPTIONS_FILE_SET+=SPEECHD
OPTIONS_FILE_UNSET+=FLITE
";

    #[test]
    fn parse_sample() {
        let f = SavedOptionsFile::parse(SAMPLE);
        assert_eq!(f.options_read, "qt5-speech-5.12.1_1");
        assert_eq!(f.complete, vec!["SPEECHD", "FLITE"]);
        assert!(f.set.contains("SPEECHD"));
        assert!(f.unset.contains("FLITE"));
    }

    #[test]
    fn render_round_trip() {
        let complete = vec!["SPEECHD".to_string(), "FLITE".to_string()];
        let enabled: BTreeSet<String> = ["SPEECHD".to_string()].into();
        let text = render("qt5-speech-5.12.1_1", &complete, &enabled);
        let f = SavedOptionsFile::parse(&text);
        assert_eq!(f.options_read, "qt5-speech-5.12.1_1");
        assert_eq!(f.complete, complete);
        assert_eq!(f.set, enabled);
        assert!(f.unset.contains("FLITE"));
    }
}
