PORTNAME=	optique
DISTVERSIONPREFIX=	v
DISTVERSION=	0.1.0
CATEGORIES=	sysutils ports-mgmt

MAINTAINER=	sdalu@sdalu.com
COMMENT=	Fast ports options configurator for poudriere and synth
# TODO: adjust when published
WWW=		https://github.com/sdalu/optique

LICENSE=	BSD2CLAUSE

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	sdalu
# TODO: the v${DISTVERSION} tag must exist upstream once published.
# Until then, generate the distfile locally from the repo:
#   git -C /root/optique archive --prefix=optique-${DISTVERSION}/ \
#       --format=tar.gz v${DISTVERSION} \
#       > ${DISTDIR}/${DIST_SUBDIR}/<name from `make -V DISTNAME`>.tar.gz
# and refresh checksums with `make makesum` after publishing for real.

CARGO_CRATES=	allocator-api2-0.2.21 \
		anstream-1.0.0 \
		anstyle-1.0.14 \
		anstyle-parse-1.0.0 \
		anstyle-query-1.1.5 \
		anstyle-wincon-3.0.11 \
		anyhow-1.0.104 \
		bitflags-2.13.1 \
		block-buffer-0.10.4 \
		cassowary-0.3.0 \
		castaway-0.2.4 \
		cfg-if-1.0.4 \
		clap-4.6.4 \
		clap_builder-4.6.2 \
		clap_derive-4.6.4 \
		clap_lex-1.1.0 \
		colorchoice-1.0.5 \
		compact_str-0.8.2 \
		cpufeatures-0.2.17 \
		crossbeam-channel-0.5.16 \
		crossbeam-utils-0.8.22 \
		crossterm-0.28.1 \
		crossterm_winapi-0.9.1 \
		crypto-common-0.1.7 \
		darling-0.23.0 \
		darling_core-0.23.0 \
		darling_macro-0.23.0 \
		digest-0.10.7 \
		either-1.17.0 \
		equivalent-1.0.2 \
		errno-0.3.14 \
		fastrand-2.5.0 \
		foldhash-0.1.5 \
		generic-array-0.14.7 \
		getrandom-0.4.3 \
		hashbrown-0.15.5 \
		heck-0.5.0 \
		ident_case-1.0.1 \
		indoc-2.0.7 \
		instability-0.3.12 \
		is_terminal_polyfill-1.70.2 \
		itertools-0.13.0 \
		itoa-1.0.18 \
		libc-0.2.189 \
		linux-raw-sys-0.4.15 \
		linux-raw-sys-0.12.1 \
		lock_api-0.4.14 \
		log-0.4.33 \
		lru-0.12.5 \
		memchr-2.8.3 \
		mio-1.2.2 \
		once_cell-1.21.4 \
		once_cell_polyfill-1.70.2 \
		parking_lot-0.12.5 \
		parking_lot_core-0.9.12 \
		paste-1.0.15 \
		proc-macro2-1.0.107 \
		quote-1.0.47 \
		r-efi-6.0.0 \
		ratatui-0.29.0 \
		redox_syscall-0.5.18 \
		rustix-0.38.44 \
		rustix-1.1.4 \
		rustversion-1.0.23 \
		ryu-1.0.23 \
		scopeguard-1.2.0 \
		serde-1.0.229 \
		serde_core-1.0.229 \
		serde_derive-1.0.229 \
		serde_json-1.0.151 \
		sha2-0.10.9 \
		signal-hook-0.3.18 \
		signal-hook-mio-0.2.5 \
		signal-hook-registry-1.4.8 \
		smallvec-1.15.2 \
		static_assertions-1.1.0 \
		strsim-0.11.1 \
		strum-0.26.3 \
		strum_macros-0.26.4 \
		syn-2.0.119 \
		syn-3.0.3 \
		tempfile-3.27.0 \
		terminal_size-0.4.4 \
		typenum-1.20.1 \
		unicode-ident-1.0.24 \
		unicode-segmentation-1.13.3 \
		unicode-truncate-1.1.0 \
		unicode-width-0.1.14 \
		unicode-width-0.2.0 \
		utf8parse-0.2.2 \
		version_check-0.9.5 \
		wasi-0.11.1+wasi-snapshot-preview1 \
		winapi-0.3.9 \
		winapi-i686-pc-windows-gnu-0.4.0 \
		winapi-x86_64-pc-windows-gnu-0.4.0 \
		windows-link-0.2.1 \
		windows-sys-0.59.0 \
		windows-sys-0.61.2 \
		windows-targets-0.52.6 \
		windows_aarch64_gnullvm-0.52.6 \
		windows_aarch64_msvc-0.52.6 \
		windows_i686_gnu-0.52.6 \
		windows_i686_gnullvm-0.52.6 \
		windows_i686_msvc-0.52.6 \
		windows_x86_64_gnu-0.52.6 \
		windows_x86_64_gnullvm-0.52.6 \
		windows_x86_64_msvc-0.52.6 \
		zmij-1.0.23

PLIST_FILES=	bin/optique \
		share/man/man8/optique.8.gz

post-install:
	@${MKDIR} ${STAGEDIR}${PREFIX}/share/man/man8
	${INSTALL_MAN} ${WRKSRC}/optique.8 ${STAGEDIR}${PREFIX}/share/man/man8/

.include <bsd.port.mk>
